---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: devopsapp
spec:
 replicas: 2
 selector:
   matchLabels:
       app: db
 template:
   metadata:
      labels: 
        app: db
   spec:
     containers:
        - name: cont-1
          image: raviart/devopsapp:dbimage
          ports:
            - containerPort: 3306
     imagePullSecrets:
          - name: dockerhub

---
apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  clusterIp: None
  selector:
    app: db
  ports:
    - port: 3306
      targetPort: 3306
